Update villanos.md
jhony117/liga-justicia pull request #2
Opened 2024-01-11 17:03 UTC by Alonso-ER

Creo que el espantapajaros es un villano muy importante

2024-01-11 17:11 UTC, jhony117 reviewed
¿quién demonios se acuerda del espanta pájaros? Ya ni el hombre gato es tan poco conocido

2024-01-11 17:19 UTC, Alonso-ER commented
> ¿quién demonios se acuerda del espanta pájaros? Ya ni el hombre gato es tan poco conocido

Okey, supongo que tu habilidad para reconocer la importancia tambien es skill issue

2024-01-12 15:43 UTC, jhony117 requested changes
hey !, por favor añade cada héroe / villano con su historia y si es posible una imagen  @Alonso-ER

2024-01-12 15:43 UTC, jhony117 commented on villanos.md
> +7. Espantapajaros
¿Por que añadiste al espanta pajaros?

2024-01-12 16:02 UTC, jhony117 commented
Increíble, ahora mismo lo añado al proyecto

2024-01-12 16:02 UTC, merged